Repository lambdalabs-eu1-webchat/webchat-frontend, pull requests merged in 2019-05, with the labels that each got.

#14 Initial actions reducers
  package-lock.json
  src/App.js
  src/ajax/url.js
  src/ajax/users.js
  src/index.js
  src/redux/actions/actionTypes.js
  src/redux/reducers/index.js
  src/redux/store.js
  src/store/actions/actionTypes.js
  src/store/actions/auth.js
  src/store/actions/users.js
  src/store/reducers/auth.js
  src/store/reducers/index.js
  src/store/reducers/users.js
Labels: bug-fix, new-feature

#16 Register login functionality
  package.json
  src/App.css
  src/App.js
  src/components/Logout.js
  src/components/NavBar.js
  src/index.js
  src/store/actions/auth.js
  src/views/Chat.js
  src/views/HomePage.js
  src/views/Login.js
  src/views/Register.js
Labels: breaking-change, new-feature

#18 Minor refactoring for Register & Login pages
  src/store/actions/auth.js
  src/views/Login.js
  src/views/Register.js
Labels: bug-fix

#20 Connect to Chats via Socket
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/store/actions/actionTypes.js
  src/store/actions/auth.js
  src/store/actions/chat.js
  src/store/actions/users.js
  src/store/reducers/chats.js
  src/store/reducers/index.js
  src/utils/paths.js
Labels: bug-fix, new-feature

#33 Small billing updates
  src/components/CheckoutForm.js
  src/components/PlanCard.js
  src/components/TeamMembersAddNewMemberModal.js
  src/store/actions/hotel.js
  src/utils/plans.js
  src/views/Billing.js
  src/views/TeamMembers.js
Labels: new-feature

#30 Employee dash chats - 1st PR
  .gitignore
  src/App.js
  src/components/ChatsList.js
  src/components/SearchInput.js
  src/components/TicketView.js
  src/store/actions/actionTypes.js
  src/store/actions/chat.js
  src/store/actions/users.js
  src/store/reducers/chats.js
  src/utils/paths.js
  src/utils/ticketStatus.js
  src/views/Chat.js
  yarn.lock
Labels: new-feature

#32 Check in
  src/App.js
  src/components/CheckoutForm.js
  src/components/EditPaymentMethodModal.js
  src/components/GuestCheckInForm.js
  src/components/GuestCheckOutForm.js
  src/index.js
  src/store/actions/actionTypes.js
  src/store/actions/rooms.js
  src/store/reducers/index.js
  src/store/reducers/rooms.js
  src/views/CheckInOrOut.js
  src/views/TeamMembers.js
Labels: new-feature

#43 Checkout name change
  src/components/EditPaymentMethodModal.js
  src/components/PaymentMethod.js
  src/components/PlanCheckout.js
  src/components/PlanCheckoutForm.js
Labels: bug-fix

#44 Search chats
  package.json
  src/components/ChatsList.js
  src/components/SearchInput.js
  src/components/chat/ChatsList.js
  src/components/chat/SearchInput.js
  src/components/chat/TicketView.js
  src/components/chat/searchMachine.js
  src/views/Chat.js
  yarn.lock
Labels: bug-fix, new-feature

#35 Registration bug fix & hotel reducers & actions
  src/App.js
  src/components/CompanySettingsRoom.js
  src/components/CompanySettingsRoomsList.js
  src/index.js
  src/store/actions/auth.js
  src/store/actions/hotel.js
  src/store/actions/rooms.js
  src/store/reducers/auth.js
  src/store/reducers/currentUser.js
  src/store/reducers/hotel.js
  src/store/reducers/index.js
  src/store/reducers/rooms.js
  src/views/CompanySettings.js
  src/views/Register.js
Labels: bug-fix, new-feature

#47 Typography error fix
  .DS_Store
  src/App.js
  src/components/layout/Footer.js
  src/components/layout/navbar/NavBar.js
  src/components/layout/navbar/SignedOutLink.js
  src/components/logout/Logout.js
Labels: bug-fix

#48 Router
  src/App.js
  src/components/Logout.js
  src/components/Router.js
  src/components/SuperAdminNav.js
  src/components/layout/navbar/NavBar.js
  src/components/layout/navbar/SignedInLink.js
  src/utils/paths.js
  src/views/Billing.js
  src/views/CompanyDash.js
  src/views/CompanySettings.js
  src/views/Login.js
  src/views/Register.js
  src/views/TeamMembers.js
Labels: new-feature

#49 Connecting chat
  src/App.js
  src/components/ChatScreen.js
  src/components/GuestCheckInForm.js
  src/components/Logout.js
  src/components/chat/ChatsList.js
  src/components/chat/TicketView.js
  src/store/actions/actionTypes.js
  src/store/actions/chat.js
  src/store/reducers/chats.js
  src/views/Chat.js
  src/views/CheckInOrOut.js
  src/views/CompanySettings.js
  src/views/Login.js
  src/views/Register.js
  src/views/TeamMembers.js
Labels: new-feature

#51 Company settings view
  src/App.css
  src/components/CompanySettingsRoom.js
  src/components/CompanySettingsRoomsList.js
  src/components/TeamMember.js
  src/components/TeamMembersList.js
  src/store/actions/actionTypes.js
  src/store/actions/rooms.js
  src/store/actions/users.js
  src/store/reducers/currentUser.js
  src/store/reducers/rooms.js
  src/store/reducers/users.js
  src/views/CompanySettings.js
  yarn.lock
Labels: new-feature

#56 ticket chats now update live
  src/App.js
  src/store/actions/actionTypes.js
  src/store/actions/chat.js
  src/store/reducers/chats.js
  src/utils/paths.js
Labels: bug-fix

#58 Responsive employee dash
  src/components/Message.js
  src/components/Messages.js
  src/components/chat/searchMachine.js
  src/views/Chat.js
Labels: new-feature

#59 Re-introduce fetching and errors in rooms reducer
  src/store/actions/rooms.js
  src/store/reducers/rooms.js
  src/views/CompanySettings.js
Labels: bug-fix

#61 temp footer fix
  src/components/Router.js
  src/components/layout/Footer.js
Labels: bug-fix

#62 Small view bugs and changed DOMAIN
  src/utils/paths.js
  src/views/CheckInOrOut.js
  src/views/CompanySettings.js
  src/views/EmployeeSettings.js
Labels: bug-fix

#63 fix domain
  src/utils/paths.js
Labels: bug-fix

#64 Upgrading nav to have number of active and queued tickets
  src/components/layout/navbar/NavBar.js
  src/store/reducers/index.js
Labels: bug-fix, new-feature

#66 fixed scrolling but with chat
  src/components/MessageComposer.js
  src/components/Messages.js
  src/components/chat/TicketView.js
  src/utils/paths.js
Labels: bug-fix

#70 QR code generation
  package.json
  src/components/GuestCheckInForm.js
  src/store/actions/actionTypes.js
  yarn.lock
Labels: new-feature

#71 Chat bugs
  package.json
  src/App.js
  src/components/ChatScreen.js
  src/components/GuestCheckInForm.js
  src/components/reusable/Tabs.js
  src/store/reducers/chats.js
  src/utils/paths.js
  src/views/Chat.js
  yarn.lock
Labels: bug-fix, new-feature

#76 Marketing page
  .DS_Store
  public/index.html
  src/assets/chatting.svg
  src/assets/staff.svg
  src/index.css
  src/theme/styledTheme.js
  src/views/HomePage.js
Labels: new-feature

#74 Send email on checkout
  package.json
  src/components/GuestCheckOutForm.js
  src/utils/paths.js
  yarn.lock
Labels: new-feature

#81 Added name-clear on checkin
  src/components/GuestCheckInForm.js
Labels: bug-fix

#78 Rating closed chat
  src/components/ChatScreen.js
  src/components/Messages.js
  src/components/RatingMessage.js
  src/components/Router.js
  src/components/SuperAdminNav.js
  src/components/layout/navbar/NavBar.js
  src/components/layout/navbar/SignedInLink.js
  src/store/reducers/chats.js
  src/views/CompanyDash.js
  src/views/Login.js
Labels: new-feature

#83 Footer styling
  src/components/layout/Footer.js
  src/components/layout/navbar/logo2.svg
  src/theme/styledTheme.js
Labels: new-feature

#86 Translate chat
  src/components/ChatScreen.js
  src/components/GuestCheckInForm.js
  src/components/MessageComposer.js
  src/components/reusable/Tabs.js
  src/store/actions/actionTypes.js
  src/store/actions/chat.js
  src/store/reducers/chats.js
  src/utils/paths.js
  src/views/Chat.js
  src/views/CompanySettings.js
Labels: new-feature

#102 Navbar styling fix
  src/App.css
  src/components/layout/Footer.js
  src/components/layout/navbar/NavBar.js
  src/components/layout/navbar/SignedInLink.js
  src/components/layout/navbar/SignedOutLink.js
Labels: new-feature

#103 Restriction modal
  package.json
  src/components/GuestCheckOutForm.js
  src/components/TeamMember.js
  src/components/TeamMembersAddNewMemberModal.js
  src/components/reusable/RestrictedModal.js
  src/theme/modalTheme.js
  src/views/Billing.js
  src/views/EmployeeSettings.js
  yarn.lock
Labels: new-feature

#105 Company settings ux
  src/components/CompanySettingsRoom.js
  src/components/CompanySettingsRoomsList.js
  src/store/actions/rooms.js
  src/views/CompanySettings.js
Labels: bug-fix, new-feature

#104 Ux check in
  src/App.css
  src/components/GuestCheckInForm.js
  src/components/GuestCheckOutForm.js
  src/components/layout/Footer.js
  src/components/layout/navbar/NavBar.js
  src/views/CheckInOrOut.js
Labels: bug-fix

#110 Fixed nav bar for specific user types
  src/components/Router.js
  src/components/layout/navbar/NavBar.js
Labels: bug-fix

#111 Login styling
  src/App.js
  src/views/CompanySettings.js
  src/views/Login.js
  src/views/Register.js
Labels: bug-fix

#114 Translate modal
  src/components/ChatScreen.js
  src/components/TranslateModal.js
  src/theme/modalTheme.js
Labels: styling

#115 fix a bug with employee login
  src/components/Router.js
Labels: bug-fix

#116 Registration UX
  src/store/actions/actionTypes.js
  src/store/actions/auth.js
  src/store/reducers/index.js
  src/store/reducers/loading.js
  src/utils/messages.js
  src/views/Register.js
Labels: new-feature

#119 Account settings styling
  src/App.js
  src/components/EmployeeSettingsForm.js
  src/components/layout/Footer.js
  src/views/EmployeeSettings.js
  src/views/HomePage.js
  src/views/Register.js
Labels: styling

#113 Changes requested chat styles
  src/components/ChatScreen.js
  src/components/ChatScreenHeader.js
  src/components/Message.js
  src/components/MessageComposer.js
  src/components/chat/ChatsList.js
  src/components/chat/SearchInput.js
  src/components/chat/TicketView.js
  src/components/reusable/Tabs.js
  src/theme/styledTheme.js
  src/utils/paths.js
  src/views/Chat.js
Labels: bug-fix, work-in-progress

#122 Change the prop name for new API connection
  src/components/ChatScreen.js
Labels: bug-fix

#126 Netlify routing
  .prettierignore
  public/_redirects
  src/utils/paths.js
Labels: breaking-change, bug-fix

#132 Company settings styling
  src/App.css
  src/components/CompanySettingsRoom.js
  src/components/CompanySettingsRoomsList.js
  src/components/SuperAdminNav.js
  src/theme/styledTheme.js
  src/views/CompanyDash.js
  src/views/CompanySettings.js
Labels: styling

#134 Nav bug fix
  src/components/layout/navbar/NavBar.js
  src/components/layout/navbar/SignedInLink.js
Labels: styling

#136 check in/out loaders placed
  src/App.css
  src/components/GuestCheckInForm.js
  src/components/GuestCheckOutForm.js
  src/components/TeamMembersList.js
  src/components/reusable/ConfirmModal.js
  src/views/CheckInOrOut.js
Labels: styling

#142 Billing styling
  src/components/CardDetails.js
  src/components/EditPaymentMethodModal.js
  src/components/PaymentMethod.js
  src/components/PlanCard.js
  src/components/PlanCards.js
  src/components/PlanCheckout.js
  src/components/PlanCheckoutForm.js
  src/components/TranslateModal.js
  src/theme/modalTheme.js
  src/views/Billing.js
Labels: styling

#144 Check in styling
  public/favicon.ico
  src/App.css
  src/components/CompanySettingsRoom.js
  src/components/CompanySettingsRoomsList.js
  src/components/EmployeeSettingsForm.js
  src/components/GuestCheckInForm.js
  src/components/GuestCheckOutForm.js
  src/components/TeamMember.js
  src/components/TeamMembersAddNewMemberModal.js
  src/components/TeamMembersList.js
  src/views/CheckInOrOut.js
  src/views/CompanySettings.js
  src/views/TeamMembers.js
Labels: styling

#140 Team members styling
  src/components/TeamMembersList.js
Labels: styling

#139 Spinners
  src/components/CompanySettingsRoom.js
  src/components/CompanySettingsRoomsList.js
  src/components/EditPaymentMethodModal.js
  src/components/EmployeeSettingsForm.js
  src/components/GuestCheckInForm.js
  src/components/GuestCheckOutForm.js
  src/components/PaymentMethod.js
  src/components/PlanCard.js
  src/components/PlanCards.js
  src/components/PlanCheckout.js
  src/components/PlanCheckoutForm.js
  src/components/TeamMember.js
  src/components/TeamMembersAddNewMemberModal.js
  src/components/TeamMembersList.js
  src/components/reusable/Spinner.js
  src/store/actions/actionTypes.js
  src/store/actions/auth.js
  src/store/actions/hotel.js
  src/store/actions/rooms.js
  src/store/actions/subscription.js
  src/store/actions/users.js
  src/store/reducers/loading.js
  src/theme/styledTheme.js
  src/views/Billing.js
  src/views/CheckInOrOut.js
  src/views/CompanyDash.js
  src/views/CompanySettings.js
  src/views/EmployeeSettings.js
  src/views/Login.js
  src/views/Register.js
  src/views/TeamMembers.js
Labels: bug-fix, new-feature

#146 Routing fixes
  src/components/PlanCheckoutForm.js
  src/components/Router.js
  src/store/actions/actionTypes.js
  src/store/actions/rooms.js
  src/store/reducers/rooms.js
  src/views/Login.js
Labels: bug-fix

#154 Changing chat dash
  src/components/Message.js
  src/components/chat/TicketView.js
  src/components/reusable/Tabs.js
  src/views/Chat.js
Labels: styling

#150 Styling changes
  src/components/CardDetails.js
  src/components/PaymentMethod.js
  src/components/PlanCard.js
  src/components/PlanCards.js
  src/components/layout/navbar/NavBar.js
  src/views/Billing.js
Labels: styling

#157 Room list upload
  src/components/CompanySettingsRoom.js
  src/components/CompanySettingsRoomsList.js
  src/views/CompanySettings.js
Labels: bug-fix, new-feature

#159 Add cursor for clickable items & make small changes to chat dash
  .DS_Store
  src/App.js
  src/components/CompanySettingsRoom.js
  src/components/GuestCheckInForm.js
  src/components/GuestCheckOutForm.js
  src/components/RatingMessage.js
  src/components/TeamMember.js
  src/components/chat/ChatsList.js
  src/components/chat/SearchInput.js
  src/components/chat/TicketView.js
  src/components/reusable/Tabs.js
  src/theme/styledTheme.js
  src/views/Chat.js
Labels: styling

#173 Prop type changes/other fixed
  src/components/EmployeeSettingsForm.js
  src/components/PlanCheckout.js
  src/components/TeamMembersList.js
  src/components/layout/navbar/SignedInLink.js
  src/views/EmployeeSettings.js
Labels: bug-fix

#174 Add duplicate rooms continuous loading
  src/store/actions/rooms.js
Labels: bug-fix

#180 Too many users modal
  src/components/TeamMember.js
  src/components/TeamMembersAddNewMemberModal.js
  src/components/TeamMembersList.js
  src/views/TeamMembers.js
Labels: bug-fix

#181 Billing fix
  src/App.js
  src/components/CardDetails.js
  src/components/EditPaymentMethodModal.js
  src/components/Messages.js
  src/components/PaymentMethod.js
  src/components/PlanCards.js
  src/components/PlanCheckout.js
  src/components/PlanCheckoutForm.js
  src/components/Router.js
  src/theme/modalTheme.js
  src/utils/paths.js
  src/views/Billing.js
  src/views/Chat.js
  src/views/CheckInOrOut.js
  src/views/Login.js
Labels: bug-fix

#184 Styling for chat dash in mobile view and chat buttons
  src/components/ChatScreen.js
  src/components/ChatScreenHeader.js
  src/components/Message.js
  src/components/MessageComposer.js
  src/components/Messages.js
  src/components/chat/SearchInput.js
  src/components/chat/TicketView.js
  src/components/reusable/Tabs.js
  src/index.css
  src/theme/styledTheme.js
Labels: bug-fix, styling

#187 Modals styling
  src/components/CardDetails.js
  src/components/CompanySettingsRoomsList.js
  src/components/EmployeeSettingsForm.js
  src/components/GuestCheckInForm.js
  src/components/GuestCheckOutForm.js
  src/components/MessageComposer.js
  src/components/PlanCard.js
  src/components/PlanCheckout.js
  src/components/PlanCheckoutForm.js
  src/components/reusable/ConfirmModal.js
  src/components/reusable/RestrictedModal.js
  src/theme/modalTheme.js
  src/views/CompanySettings.js
  src/views/HomePage.js
  src/views/Login.js
  src/views/Register.js
  src/views/TeamMembers.js
Labels: styling

#176 Removing moto
  src/components/EmployeeSettingsForm.js
  src/index.js
  src/store/actions/auth.js
  src/store/actions/hotel.js
  src/store/actions/users.js
  src/store/reducers/currentUser.js
  src/store/reducers/hotel.js
  src/views/CompanySettings.js
  src/views/EmployeeSettings.js
  src/views/Register.js
Labels: HIGH

#158 Translate idea
  src/App.js
  src/components/ChatScreen.js
  src/components/GuestCheckOutForm.js
  src/components/Message.js
  src/components/MessageComposer.js
  src/components/Messages.js
  src/store/actions/actionTypes.js
  src/store/actions/chat.js
  src/store/reducers/chats.js
  src/utils/paths.js
  src/views/CheckInOrOut.js
Labels: new-feature

#185 Add Team Modal - UX
  src/components/TeamMembersAddNewMemberModal.js
  src/components/layout/navbar/SignedInLink.js
  src/store/actions/users.js
  src/utils/messages.js
  src/views/TeamMembers.js
Labels: bug-fix

#193 make all register buttons go to register when clicked anywhere on button
  src/components/ChatScreen.js
  src/views/HomePage.js
Labels: bug-fix

#194 Spinner ux changes
  src/components/CompanySettingsRoom.js
  src/components/CompanySettingsRoomsList.js
  src/components/EmployeeSettingsForm.js
  src/components/GuestCheckInForm.js
  src/components/PlanCheckoutForm.js
  src/components/TeamMember.js
  src/components/TeamMembersAddNewMemberModal.js
  src/components/chat/TicketView.js
  src/components/reusable/Spinner.js
  src/store/actions/actionTypes.js
  src/store/actions/chat.js
  src/store/reducers/loading.js
  src/utils/paths.js
  src/views/CompanySettings.js
  src/views/EmployeeSettings.js
  src/views/Login.js
  src/views/Register.js
Labels: bug-fix

#198 Small billing view fix
  src/components/CardDetails.js
Labels: bug-fix

#195 Restriction modal implementation
  src/components/GuestCheckOutForm.js
  src/utils/paths.js
  src/views/CompanySettings.js
Labels: bug-fix

#197 Views styling
  src/components/CardDetails.js
  src/components/CompanySettingsRoomsList.js
  src/components/PaymentMethod.js
  src/components/PlanCard.js
  src/components/PlanCards.js
  src/components/PlanCheckout.js
  src/components/PlanCheckoutForm.js
  src/theme/styledTheme.js
  src/views/Billing.js
  src/views/HomePage.js
  src/views/Login.js
  src/views/Register.js
Labels: styling

#203 FE - Restricted routes
  src/components/GuestCheckInForm.js
  src/components/GuestCheckOutForm.js
  src/store/actions/auth.js
  src/store/actions/chat.js
  src/store/actions/hotel.js
  src/store/actions/rooms.js
  src/store/actions/subscription.js
  src/store/actions/users.js
  src/utils/axiosConfig.js
  src/utils/paths.js
  src/views/CheckInOrOut.js
  src/views/CompanySettings.js
Labels: breaking-change

#199 Employee settings feedback
  src/components/EmployeeSettingsForm.js
  src/store/actions/users.js
  src/store/reducers/currentUser.js
  src/store/reducers/users.js
  src/utils/messages.js
  src/views/EmployeeSettings.js
Labels: bug-fix

#202 Change the order of the buttons so it is consistent with the settings…
  src/utils/plans.js
  src/views/CompanySettings.js
  src/views/HomePage.js
Labels: LOW

#206 Get language on translate send
  src/components/ChatScreen.js
  src/components/Message.js
  src/components/MessageComposer.js
  src/components/chat/TicketView.js
  src/store/actions/chat.js
  src/utils/decodeHtml.js
Labels: LOW, bug-fix

#207 Style print
  src/App.css
  src/components/CompanySettingsRoomsList.js
  src/components/GuestCheckInForm.js
Labels: styling

#200 Modals
  public/index.html
  src/App.js
  src/components/EmployeeSettingsForm.js
  src/components/TeamMembersAddNewMemberModal.js
  src/components/TeamModal.js
  src/views/CompanySettings.js
  src/views/HomePage.js
  src/views/TeamMembers.js
Labels: HIGH

#208 Axios config bug
  src/components/GuestCheckInForm.js
  src/components/GuestCheckOutForm.js
  src/store/actions/rooms.js
  src/utils/axiosConfig.js
  src/views/CheckInOrOut.js
Labels: bug-fix

#209 Terms privacy
  src/assets/not-found.svg
  src/components/Router.js
  src/components/layout/Footer.js
  src/utils/paths.js
  src/views/NotFound.js
  src/views/PrivacyPage.js
  src/views/TermsPage.js
Labels: styling

#215 Scroll chat
  src/components/ChatScreen.js
  src/components/Messages.js
Labels: bug-fix

#216 Change button shadow on hover & add transitions where missing
  src/components/ChatScreen.js
  src/components/MessageComposer.js
  src/components/Messages.js
  src/components/layout/Footer.js
  src/theme/styledTheme.js
  src/views/Login.js
Labels: styling

#212 About page
  src/avatar/connor.jpg
  src/avatar/diana.jpg
  src/avatar/luke.jpg
  src/avatar/mark.jpg
  src/avatar/pavol.PNG
  src/avatar/tale.jpg
  src/avatar/talent.jpeg
  src/components/Router.js
  src/utils/paths.js
  src/views/About.js
Labels: MEDIUM

#219 Fix margin issue on Privacy page
  src/views/PrivacyPage.js
Labels: styling

#221 Final changes
  src/avatar/talent.jpeg
  src/index.js
  src/utils/paths.js
  src/views/About.js
Labels: bug-fix
